### ISSUE TITLE
what happened to terminus ? 

### ISSUE THREAD

**Issue by moda20** [beclab/Olares#641]
where did it go ? i had this tab open and suddenly it changed to a completely different project,

**Comment by cal-weng** [comment]
Hi, @moda20 Thanks for following us along and sorry for the confusion. We just finished our rebranding from Terminus to Olares recently due to some concerns on identity and trade mark registration. We are going to spread the word on different channels next week. You can learn more in our rebranding blog  [Terminus is Now Olares | Medium](https://olares.medium.com/terminus-is-now-olares-2c3bf782f9d1).
Don't worry - the only thing changed is the branding names. The project and our mission remain unchanged.
