### ISSUE TITLE
why I have to use larepass?

### ISSUE THREAD

**Issue by kunthar** [beclab/Olares#719]
Why I have to get olares id to run olares?
I have no idea what is your mobile app does. I have no idea why  are you collecting my info.
Why I can't use my own domain at zero point?
Do you believe you can have more users with this nonsence policy?
If you wanna make money fine, go get it but please don't pretend like you democratizing the way of application usage.
It is not right.

**Comment by fnalways** [comment]
Hi @kunthar 

Thank you for raising your cocnerns. We appreciate you taking the time to let us know how you feel. Let me try to explain why things work the way they do and hopefully clear up some of your concerns.

## Why do you need LarePass?
LarePass isn’t just a random app we’re asking you to install. It’s designed to give you control over your identity and data in a decentralized way. Here’s what it does:

1. When you create an account in Olares, the account information is stored on the blockchain. Your private key (used to manage your identity and data) is stored securely in LarePass, on your device. Only you have access to it. We don’t have access to your private key, which ensures your data stays private and secure.
2. After registering, we assign you a free domain (e.g., `yourname.olares.com`) and an HTTPS certificate. This ensures you can access your Olares system securely over HTTPS rather than just using an IP address.

LarePass also integrates advanced security features such as Two-Factor Authentication (2FA) and VPN access (via Tailscale). 

We believe this approach strikes a balance between security, usability (though we acknowledge there’s room for improvement), and decentralization.

## How to set up custom domain?

Actually, you can use your own domain! Olares has supported custom domains from the very start. The setup process is straightforward and detailed in our documentation: [Set up a custom domain](https://docs.olares.xyz/manual/space/host-domain.html).

That said, we’re also working on releasing a more detailed tutorial soon to make this process even easier to follow.

## Why this approach? (Why bother)
Our vision for Olares is built around the future internet architecture of **Blockchain - Edge - Client**:

- The Client (LarePass) is where you securely manage your private keys.
- The Blockchain stores your decentralized identity and system data.
- The Edge allows you to host your applications and access them via secure domains.

We’re committed to transparency. By following this architecture, we ensure that your identity, data, and applications remain decentralized, secure, and under your control.

Olares is open sourced, which means anyone can set it up and use it for free. We’re not collecting your data or trying to lock you into a paid service.

In the future, we plan to offer optional hardware for users who prefer a plug-and-play experience. However, if you’re comfortable managing everything yourself, there’s no need to pay for anything.

I completely understand that these steps might feel restrictive or unnecessary at first. We’re constantly working to improve based on feedback like yours. If there’s anything else you’d like to share or any part of the process that’s unclear, please let us know.

Thanks again for reaching out, and I hope this clears things up!

**Comment by kunthar** [comment]
I've read your docs before writing here. So, please stop acting like a half chatgpt.   

> When you create an account in Olares, the account information is stored on the blockchain. Your private key (used to manage your identity and data) is stored securely in LarePass, on your device. Only you have access to it. We don’t have access to your private key, which ensures your data stays private and secure.
- Where is LarePass mobile source code? I could believe by checking the source code of this app. 
- You have a connection to  *my mobile phone*.  Who can tell that you don't send my phone number and other personal details to somewhere unknown with mobile app? 
- How can I assure my key is private? 

> After registering, we assign you a free domain (e.g., yourname.olares.com) and an HTTPS certificate. This ensures you can access your Olares system securely over HTTPS rather than just using an IP address.
- what happens if olares domain expired? 
- why should I use this domain? i can't use custom domain without having  olares account. why not?

**Comment by fnalways** [comment]
Hi @kunthar 

Thanks for sharing your concerns, and I appreciate the opportunity to address them. Data privacy and transparency are critical topics, so I'll do my best to answer your questions:

> * Where is LarePass mobile source code? I could believe by checking the source code of this app.

We open-sourced LarePass earlier this year (April to Oct.), but we’ve temporarily made the repository private. This is because we’re transitioning to the AGPL v3 license and reviewing our code of conduct. The plan is to have it public again by _Feb. 2025_. All other code that runs on edge devices are publicly accessible.

> * You have a connection to  _my mobile phone_.  Who can tell that you don't send my phone number and other personal details to somewhere unknown with mobile app?

The security of your phone number is handled natively by your device OS itself (Android or iOS). LarePass _does not_ ask for access to your phone number or other personal details. You can review the permissions requested by the app. But feel free to reach out if you‘d like clarification about any specific permissions.

> * How can I assure my key is private?

You’re right, words alone won’t be enough to provide assurance. This is why we believe that open-sourcing LarePass will help address this concern. Once the code is public again, you’ll be able to verify for yourself.

> * what happens if olares domain expired?

Olares domain does not expire like traditional domains. So there‘s no risk of losing access due to expiration.

> * why should I use this domain? i can't use custom domain without having  olares account. why not?

LarePass is here to simplify things for those who want a straightforward solution. It's meant to make things easier while avoidng the technical challenges like setting up domains. if you’re not comfortable using LarePass, you can absolutely build your own client. We’re happy to assist with that.

We understand trust takes time and transparency. Your questions show that you care deeply about data privacy, and we share that commitment. Again thanks for your time to share your concerns with us.

**Comment by kunthar** [comment]
https://media1.tenor.com/m/OWULNY2jhloAAAAd/seinfeld-elaine-benes.gif
