### ISSUE TITLE
[ Question ] How to upgrade to 1.11.0

### ISSUE THREAD

**Issue by djbobyd** [beclab/Olares#810]
Hi I saw there is a new version 1.11.0 released couple of days ago. 
Unfortunately I do not see it in the settings and cannot update to it. 
Previous updates were shown on the Settings->System->Version page and I was able to upgrade between releases without issues. 
However for some reason 1.11.0 is not available. Is this interntional or could there be something wrong with the update check?
Is there  some way to force the system to check for updates? I couldn't find any.
My current version is 1.10.5
Thanks!

**Comment by pengpeng** [comment]
1.10.5 couldnot be upgraded to version 1.11.0

Our upgrade program is not good enough yet - it can only handle PATCH version upgrades and cannot upgrade across MINOR versions.

If you want to try version 1.11.0, you'll need to uninstall version 1.10.5 first and then reinstall. Since both versions share many of the same images, the installation process will be much faster than your first installation.

**Comment by djbobyd** [comment]
Thanks!
Does this mean that everything installed will be deleted ? I didn't find a backup option...

**Comment by pengpeng** [comment]
We are developing backup-related features, which will be gradually released in the upcoming versions.

**Comment by djbobyd** [comment]
OK, I will keep it in the lab for the moment. As soon as you have it more stable I can try it in production :)
Thanks!
